- name: "LAUNCE THE INSTANCES THROUGH ANCIBLE"
  hosts: local
  vars:
    subnetid: subnet-0074974b2221ebe41
    secgrpid: sg-0702ac86b9ebe68f7 #sg-0702ac86b9ebe68f7
    amid: ami-09c813fb71547fc4f #ami-09c813fb71547fc4f
    zone: kondarao.online
    instances:
    - mysql
    - frontend
    - backed
  connection: local
  become: yes
  tasks:
  - name: instances lanch
    amazon.aws.ec2_instance:
      name: "{{item}}"
      region: us-east-1
      vpc_subnet_id: "{{subnetid}}"
      instance_type: "t3.micro"
      security_group: "{{secgrpid}}"
      image_id: "{{amid}}"
    loop: "{{instances}}"
    register: ec2_instances
    
  - name: print the ec2-instances data
    ansible.builtin.debug:
      msg: "{{ec2_instances}}"
  - name: route53 setting records
    amazon.aws.route53:
      state: present
      zone: "{{zone}}"
      record: "{{item.item}}.{{zone}}"
      type: A
      ttl: 1
      value: "{{item.instances[0].private_ip_address}}"
      wait: true
      overwrite: true
    loop: "{{ec2_instances.results}}" 